version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=ranKeyStrong(!)Password
    ports:
      - 1433:1433
    volumes:
      - mssql-db:/var/opt/mssql
volumes:
  mssql-db: